### ISSUE TITLE
hashMap error

### ISSUE THREAD

**Issue by nitrag** [hiddestokvis/TitaniumBeaconTransmitter#1]
ArrayMap/Hashmap error

Very interested in this module!

```
[WARN] :   W/System.err: java.lang.ClassCastException: java.util.HashMap cannot be cast to android.util.ArrayMap
[WARN] :   W/System.err:    at com.neverhide.bletransmitter.BleTransmitterModule.BeaconMe(BleTransmitterModule.java:93)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:145)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  TiExceptionHandler: (main) [140,57778] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,57778] - In alloy/controllers/generate.js:277,23
[ERROR] :  TiExceptionHandler: (main) [0,57778] - Message: Uncaught Error: java.util.HashMap cannot be cast to android.util.ArrayMap
[ERROR] :  TiExceptionHandler: (main) [0,57778] - Source:         AndroidBeacon.BeaconMe({
[ERROR] :  V8Exception: Exception occurred at alloy/controllers/generate.js:277: Uncaught Error: java.util.HashMap cannot be cast to android.util.ArrayMap
```

**Comment by hiddestokvis** [comment]
I have pushed a new commit, I think this should fix things. I have also found that the module breaks in lower versions of android. As Android < 5 can't send out beacon signals anyways you don't need to include the module when the user is on an older phone. Please check for the Android version:

```
if(Ti.Platform.version >= 5) {
AndroidBeacon = require('com.neverhide.bletransmitter');
}
```

**Comment by nitrag** [comment]
Awesome!!!!

**Comment by bruce-atkinson** [comment]
This may be out of place, but any plans to convert https://github.com/youten/BLERW to titanium?

**Comment by hiddestokvis** [comment]
@RBAtkins0n maybe a little :) I don't have direct plans to convert that module to titanium, if i get around to it I might however expand this module with ranging capabilities. But there are some good android ranging modules for BLE out there!

**Comment by bruce-atkinson** [comment]
Ah, cool! Thanks for the great work!
